name: Build macOS and Windows Executables

on:
  push:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app PyQt5 python-binance

      - name: Build .app
        run: python setup.py py2app

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: FirstLayout.app
          path: dist/FirstLayout.app

  build-windows:
    runs-on: Checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pyinstaller --onefile FirstLayout.py

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: FirstLayout.exe
          path: dist/FirstLayout.exe

